#!/bin/sh
echo "Installing dependencies ..."
cd utils/parallel
go install
echo "\t... Installed parallel √"
cd ../../lsh
go install
echo "\t... Installed lsh √"
cd ../projection/rp
go install
echo "\t... Installed rp √"
cd ../fjlt
go install
echo "\t... Installed fjlt √"
cd ../../counting/counts
go install
echo "\t... Installed counts √"
cd ../../probing/gb
go install
echo "\t... Installed gb √"
cd ../../types
go install
echo "\t... Installed types √"
cd ../
go install
echo "\t... Installed rphash √"
