#!/bin/sh
echo "Installing dependencies ..."
cd utils/parallel
go install
echo "\t... Installed parallel √"
cd ../../lsh
go install
echo "\t... Installed lsh √"
cd ../projection/rp
go install
echo "\t... Installed rp √"
cd ../../hash/murmur
go install
echo "\t... Installed murmur √"
cd ../../utils/vectors
go install
echo "\t... Installed vectors √"
cd ../../decoder/spherical
go install
echo "\t... Installed spherical √"
cd ../../types
go install
echo "\t... Installed types √"
cd ../
go install
echo "\t... Installed rphash √"
echo "Finished installing dependencies √"
